---
- name: Install NFS server
  ansible.builtin.apt:
    name:
      - nfs-kernel-server
      - nfs-common
    state: present
    lock_timeout: 300
  retries: 3
  delay: 90

- name: Create shared directory
  ansible.builtin.file:
    path: /home/shared
    state: directory
    owner: vagrant
    group: vagrant
    mode: '0755'

- name: Configure NFS exports
  ansible.builtin.template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: '0644'

- name: Start and enable NFS services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - nfs-kernel-server
    - rpcbind

- name: Export NFS shares
  ansible.builtin.shell: exportfs -ra
