---
- name: Install MongoDB mongos router
  ansible.builtin.apt:
    name: mongodb-mongosh
    state: present
    lock_timeout: 300
  retries: 3
  delay: 90

- name: Create MongoDB mongos configuration
  ansible.builtin.template:
    src: mongos.conf.j2
    dest: /etc/mongos.conf
    owner: root
    group: root
    mode: '0644'

- name: Create MongoDB mongos systemd service
  ansible.builtin.template:
    src: mongos.service.j2
    dest: /etc/systemd/system/mongos.service
    owner: root
    group: root
    mode: '0644'

- name: Start MongoDB mongos router
  ansible.builtin.systemd:
    name: mongos
    state: started
    enabled: yes
    daemon_reload: yes

- name: Wait for MongoDB mongos to be ready
  ansible.builtin.wait_for:
    port: 27017
    delay: 5
    timeout: 60

- name: Add shards to MongoDB cluster
  ansible.builtin.shell: |
    mongosh --host localhost:27017 --eval "
    sh.addShard('{{ inventory_hostname }}:27018');
    sh.enableSharding('burst_a_flat');
    sh.shardCollection('burst_a_flat.sample_data_task_1', {array_task: 1});
    sh.shardCollection('burst_a_flat.sample_data_task_2', {array_task: 1});
    sh.shardCollection('burst_a_flat.sample_data_task_3', {array_task: 1});
    sh.shardCollection('burst_a_flat.sample_data_task_4', {array_task: 1});
    "
  args:
    creates: /tmp/mongodb_shards_added
  register: shard_add_result
  failed_when: shard_add_result.rc != 0 and "already exists" not in shard_add_result.stderr

- name: Debug shard addition result
  ansible.builtin.debug:
    var: shard_add_result.stdout
