---
- name: Install R and dependencies
  ansible.builtin.apt:
    name:
      - r-base
      - r-base-dev
      - r-cran-rmongodb
      - r-cran-dplyr
      - r-cran-ggplot2
      - r-cran-data.table
      - r-cran-jsonlite
      - r-cran-httr
    state: present
    lock_timeout: 300
  retries: 3
  delay: 90

- name: Install R packages via R
  ansible.builtin.shell: |
    R --slave -e "install.packages(c('mongolite', 'DBI', 'RSQLite'), repos='https://cran.rstudio.com/')"
  args:
    creates: /tmp/r_packages_installed

- name: Mark R packages as installed
  ansible.builtin.file:
    path: /tmp/r_packages_installed
    state: touch
