---
- name: Install NFS client
  ansible.builtin.apt:
    name:
      - nfs-common
    state: present
    lock_timeout: 300
  retries: 3
  delay: 90

- name: Create mount point
  ansible.builtin.file:
    path: /home/vagrant/shared/results
    state: directory
    owner: vagrant
    group: vagrant
    mode: '0755'

- name: Mount NFS share
  ansible.builtin.mount:
    path: /home/vagrant/shared/results
    src: "{{ groups['nfs_servers'][0] }}:/home/shared/results"
    fstype: nfs
    opts: defaults
    state: mounted

- name: Add NFS mount to fstab
  ansible.builtin.mount:
    path: /home/vagrant/shared/results
    src: "{{ groups['nfs_servers'][0] }}:/home/shared/results"
    fstype: nfs
    opts: defaults
    state: present
