---
- name: Install Munge
  ansible.builtin.apt:
    name:
      - munge
      - libmunge-dev
    state: present
    lock_timeout: 300
  retries: 3
  delay: 90

- name: Create munge key directory
  ansible.builtin.file:
    path: /etc/munge
    state: directory
    owner: munge
    group: munge
    mode: '0700'

- name: Check if munge key vault file exists and is encrypted
  ansible.builtin.shell: |
    if [ -f "{{ playbook_dir }}/../passwords/munge.key" ]; then
      head -1 "{{ playbook_dir }}/../passwords/munge.key" | grep -q "ANSIBLE_VAULT" && echo "encrypted" || echo "unencrypted"
    else
      echo "missing"
    fi
  register: munge_key_status
  delegate_to: localhost
  become: no

- name: Create passwords directory
  ansible.builtin.file:
    path: "{{ playbook_dir }}/../passwords"
    state: directory
    mode: '0700'
  delegate_to: localhost
  become: no
  when:
    - inventory_hostname == groups['slurm_controllers'][0]
    - munge_key_status.stdout != "encrypted"

- name: Create vault password file if missing
  ansible.builtin.shell: |
    if [ ! -f "{{ playbook_dir }}/../.vault_pass" ]; then
      head /dev/urandom | tr -dc A-Za-z0-9_ | head -c 45 > "{{ playbook_dir }}/../.vault_pass"
      chmod 600 "{{ playbook_dir }}/../.vault_pass"
      echo "Created vault password file: {{ playbook_dir }}/../.vault_pass"
    fi
  delegate_to: localhost
  become: no
  when: inventory_hostname == groups['slurm_controllers'][0]

- name: Generate new munge key (controller only)
  ansible.builtin.shell: /usr/sbin/mungekey -c
  args:
    creates: /etc/munge/munge.key
  become: yes
  when:
    - inventory_hostname == groups['slurm_controllers'][0]
    - munge_key_status.stdout != "encrypted"

- name: Set munge key permissions (controller only)
  ansible.builtin.file:
    path: /etc/munge/munge.key
    owner: munge
    group: munge
    mode: '0600'
  when: inventory_hostname == groups['slurm_controllers'][0]

- name: Copy unencrypted munge key to temporary location for encryption
  ansible.builtin.fetch:
    src: /etc/munge/munge.key
    dest: /tmp/munge_unencrypted.key
    flat: yes
  become: yes
  when:
    - inventory_hostname == groups['slurm_controllers'][0]
    - munge_key_status.stdout != "encrypted"

- name: Create MD5 hash of unencrypted munge key for verification
  ansible.builtin.shell: |
    md5sum /tmp/munge_unencrypted.key | cut -d' ' -f1 > "{{ playbook_dir }}/../passwords/munge.key.md5"
  delegate_to: localhost
  become: no
  when:
    - inventory_hostname == groups['slurm_controllers'][0]
    - munge_key_status.stdout != "encrypted"

- name: Encrypt munge key with ansible-vault
  ansible.builtin.shell: |
    ansible-vault encrypt /tmp/munge_unencrypted.key --vault-password-file "{{ playbook_dir }}/../.vault_pass" --output "{{ playbook_dir }}/../passwords/munge.key"
  delegate_to: localhost
  become: no
  when:
    - inventory_hostname == groups['slurm_controllers'][0]
    - munge_key_status.stdout != "encrypted"

- name: Deploy munge key from vault to controller
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../passwords/munge.key"
    dest: /etc/munge/munge.key
    owner: munge
    group: munge
    mode: '0600'
  become: yes
  when:
    - inventory_hostname == groups['slurm_controllers'][0]
    - munge_key_status.stdout == "encrypted"

- name: Deploy munge key from vault to all nodes
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../passwords/munge.key"
    dest: /etc/munge/munge.key
    owner: munge
    group: munge
    mode: '0600'
  become: yes
  when:
    - inventory_hostname != groups['slurm_controllers'][0]
    - munge_key_status.stdout == "encrypted"

- name: Copy munge key from controller to all nodes (fallback)
  ansible.builtin.copy:
    src: /etc/munge/munge.key
    dest: /etc/munge/munge.key
    owner: munge
    group: munge
    mode: '0600'
    remote_src: yes
  when:
    - munge_key_status.stdout != "encrypted"
  delegate_to: "{{ groups['slurm_controllers'][0] }}"

- name: Create MD5 hash of controller munge key for fallback verification
  ansible.builtin.shell: |
    md5sum /etc/munge/munge.key | cut -d' ' -f1 > "{{ playbook_dir }}/../passwords/munge.key.md5"
  delegate_to: localhost
  become: no
  when:
    - inventory_hostname == groups['slurm_controllers'][0]
    - munge_key_status.stdout != "encrypted"

- name: Verify munge key MD5 hash on all nodes
  ansible.builtin.shell: |
    if [ -f "{{ playbook_dir }}/../passwords/munge.key.md5" ]; then
      expected_md5=$(cat "{{ playbook_dir }}/../passwords/munge.key.md5")
      actual_md5=$(md5sum /etc/munge/munge.key | cut -d' ' -f1)
      if [ "$expected_md5" = "$actual_md5" ]; then
        echo "Munge key verification PASSED for {{ inventory_hostname }}"
      else
        echo "Munge key verification FAILED for {{ inventory_hostname }}: expected $expected_md5, got $actual_md5"
        exit 1
      fi
    else
      echo "No MD5 hash file found for verification on {{ inventory_hostname }}"
      exit 1
    fi
  register: munge_key_verification
  failed_when: munge_key_verification.rc != 0

- name: Display munge key verification results
  ansible.builtin.debug:
    msg: |
      Munge Key Verification Results:
      {% for host in ansible_play_hosts %}
      {{ host }}: {{ hostvars[host]['munge_key_verification']['stdout'] }}
      {% endfor %}

- name: Start and enable munge service
  ansible.builtin.systemd:
    name: munge
    state: started
    enabled: yes
