---
- name: Install Munge
  ansible.builtin.apt:
    name:
      - munge
      - libmunge-dev
    state: present
    lock_timeout: 300
  retries: 3
  delay: 90

- name: Create munge key directory
  ansible.builtin.file:
    path: /etc/munge
    state: directory
    owner: munge
    group: munge
    mode: '0700'

- name: Generate munge key (controller only)
  ansible.builtin.shell: |
    if [ ! -f /etc/munge/munge.key ]; then
      /usr/sbin/mungekey -c
    fi
  args:
    creates: /etc/munge/munge.key
  become: yes
  when: inventory_hostname == groups['slurm_controllers'][0]

- name: Set munge key permissions (controller only)
  ansible.builtin.file:
    path: /etc/munge/munge.key
    owner: munge
    group: munge
    mode: '0400'
  when: inventory_hostname == groups['slurm_controllers'][0]

- name: Copy munge key from controller to all nodes
  ansible.builtin.copy:
    src: /etc/munge/munge.key
    dest: /etc/munge/munge.key
    owner: munge
    group: munge
    mode: '0400'
    remote_src: yes
  when: inventory_hostname == groups['slurm_controllers'][0]
  delegate_to: "{{ item }}"
  loop: "{{ groups['all'] }}"

- name: Start and enable munge service
  ansible.builtin.systemd:
    name: munge
    state: started
    enabled: yes
