---
- name: Remove conflicting default routes for network2 hosts
  ansible.builtin.shell: |
    # Remove any default routes via 192.168.121.1 (Vagrant NAT)
    ip route del default via 192.168.121.1 dev eth0 2>/dev/null || true
  register: route_result
  changed_when: route_result.rc == 0
  when: inventory_hostname in groups['network2']

- name: Configure default route for network2 hosts
  ansible.builtin.shell: |
    # Add default route to management-node if not already present
    ip route add default via 192.168.60.11 2>/dev/null || true
  register: route_result
  changed_when: route_result.rc == 0
  when: inventory_hostname in groups['network2']

- name: Configure route to network1 via management-node
  ansible.builtin.shell: |
    # Add route to network1 via management-node if not already present
    ip route add 192.168.50.0/24 via 192.168.60.11 2>/dev/null || true
  register: route_result
  changed_when: route_result.rc == 0
  when: inventory_hostname in groups['network2']

- name: Configure route to network2 via management-node for network1 hosts
  ansible.builtin.shell: |
    # Add route to network2 via management-node if not already present
    ip route add 192.168.60.0/24 via 192.168.50.11 2>/dev/null || true
  register: route_result
  changed_when: route_result.rc == 0
  when: inventory_hostname in groups['network1']
